<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config[
  <!ELEMENT lockss-config (if|property)+>
  <!ELEMENT property (property|list|value|if)*>
  <!ELEMENT list (value)+>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT test EMPTY>
  <!ELEMENT and (and|or|not|test)*>
  <!ELEMENT or (and|or|not|test)*>
  <!ELEMENT not (and|or|not|test)*>
  <!ELEMENT if (and|or|not|then|else|property)*>
  <!ELEMENT then (property)*>
  <!ELEMENT else (property)*>
  <!ATTLIST property name CDATA #REQUIRED>
  <!ATTLIST property value CDATA #IMPLIED>
  <!ATTLIST test hostname CDATA #IMPLIED>
  <!ATTLIST test group CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST test daemonVersion CDATA #IMPLIED>
  <!ATTLIST test platformVersionMin CDATA #IMPLIED>
  <!ATTLIST test platformVersionMax CDATA #IMPLIED>
  <!ATTLIST test platformVersion CDATA #IMPLIED>
  <!ATTLIST if hostname CDATA #IMPLIED>
  <!ATTLIST if group CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST if daemonVersion CDATA #IMPLIED>
  <!ATTLIST if platformVersionMin CDATA #IMPLIED>
  <!ATTLIST if platformVersionMax CDATA #IMPLIED>
  <!ATTLIST if platformVersion CDATA #IMPLIED>
]>

<lockss-config>

  <property name="org.lockss.title">

    <property name="ACSChemicalBiology1">
      <property name="title" value="ACS Chemical Biology Volume 1" />
      <property name="journalTitle" value="ACS Chemical Biology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="acbcct" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="1" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemicalBiology2">
      <property name="title" value="ACS Chemical Biology Volume 2" />
      <property name="journalTitle" value="ACS Chemical Biology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="acbcct" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="2" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials1">
      <property name="title" value="Chemistry of Materials Volume 1" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="1" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials2">
      <property name="title" value="Chemistry of Materials Volume 2" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="2" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials3">
      <property name="title" value="Chemistry of Materials Volume 3" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="3" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials4">
      <property name="title" value="Chemistry of Materials Volume 4" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="4" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials5">
      <property name="title" value="Chemistry of Materials Volume 5" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="5" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials6">
      <property name="title" value="Chemistry of Materials Volume 6" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="6" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials7">
      <property name="title" value="Chemistry of Materials Volume 7" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="7" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials8">
      <property name="title" value="Chemistry of Materials Volume 8" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="8" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials9">
      <property name="title" value="Chemistry of Materials Volume 9" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="9" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials10">
      <property name="title" value="Chemistry of Materials Volume 10" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="10" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials11">
      <property name="title" value="Chemistry of Materials Volume 11" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="11" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials12">
      <property name="title" value="Chemistry of Materials Volume 12" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="12" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials13">
      <property name="title" value="Chemistry of Materials Volume 13" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="13" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials14">
      <property name="title" value="Chemistry of Materials Volume 14" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="14" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials15">
      <property name="title" value="Chemistry of Materials Volume 15" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="15" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials16">
      <property name="title" value="Chemistry of Materials Volume 16" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="16" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials17">
      <property name="title" value="Chemistry of Materials Volume 17" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="17" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials18">
      <property name="title" value="Chemistry of Materials Volume 18" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="18" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSChemistryofMaterials19">
      <property name="title" value="Chemistry of Materials Volume 19" />
      <property name="journalTitle" value="Chemistry of Materials" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="cmatex" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="19" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology1">
      <property name="title" value="Environmental Science &amp; Technology Volume 1" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="1" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology2">
      <property name="title" value="Environmental Science &amp; Technology Volume 2" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="2" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology3">
      <property name="title" value="Environmental Science &amp; Technology Volume 3" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="3" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology4">
      <property name="title" value="Environmental Science &amp; Technology Volume 4" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="4" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology5">
      <property name="title" value="Environmental Science &amp; Technology Volume 5" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="5" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology6">
      <property name="title" value="Environmental Science &amp; Technology Volume 6" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="6" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />
    </property>

    <property name="ACSEnvironmentalScienceandTechnology7">
      <property name="title" value="Environmental Science &amp; Technology Volume 7" />
      <property name="journalTitle" value="Environmental Science &amp; Technology" />
      <property name="plugin" value="org.lockss.plugin.acs.ClockssAmericanChemicalSocietyPlugin" />
      <property name="param.1">
        <property name="key" value="base_url" />
        <property name="value" value="http://pubs3.acs.org/" />
      </property>
      <property name="param.2">
        <property name="key" value="article_url" />
        <property name="value" value="http://pubs.acs.org/" />
      </property>
      <property name="param.3">
        <property name="key" value="journal_key" />
        <property name="value" value="esthag" />
      </property>
      <property name="param.4">
        <property name="key" value="volume_name" />
        <property name="value" value="7" />
      </property>
      <property name="attributes.publisher" value="American Chemical Society" />