<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
  <!ELEMENT lockss-config (if|property)+>
  <!ELEMENT property (property|list|value|if)*>
  <!ELEMENT list (value)+>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT test EMPTY>
  <!ELEMENT and (and|or|not|test)*>
  <!ELEMENT or (and|or|not|test)*>
  <!ELEMENT not (and|or|not|test)*>
  <!ELEMENT if (and|or|not|then|else|property)*>
  <!ELEMENT then (property)*>
  <!ELEMENT else (property)*>
  <!ATTLIST property name CDATA #REQUIRED>
  <!ATTLIST property value CDATA #IMPLIED>
  <!ATTLIST test hostname CDATA #IMPLIED>
  <!ATTLIST test group CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST test daemonVersion CDATA #IMPLIED>
  <!ATTLIST test platformVersionMin CDATA #IMPLIED>
  <!ATTLIST test platformVersionMax CDATA #IMPLIED>
  <!ATTLIST test platformVersion CDATA #IMPLIED>
  <!ATTLIST if hostname CDATA #IMPLIED>
  <!ATTLIST if group CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST if daemonVersion CDATA #IMPLIED>
  <!ATTLIST if platformVersionMin CDATA #IMPLIED>
  <!ATTLIST if platformVersionMax CDATA #IMPLIED>
  <!ATTLIST if platformVersion CDATA #IMPLIED>
]>

<lockss-config>
  <property name="org.lockss.title">

    <property name="ClockssWiley2006">
     <property name="title" value="Wiley 2006" />
     <property name="journalTitle" value="Wiley" />
     <property name="plugin" value="org.lockss.plugin.wiley.ClockssWileyPlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://source-stage.lockss.org/sourcefiles/wiley/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
    </property>

    <property name="AIChEJournal2006">
     <property name="title" value="AIChE Journal 2006" />
     <property name="journalTitle" value="AIChE Journal" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="00011541" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

    <property name="JournalofPharmaceuticalSciences2006">
     <property name="title" value="Journal of Pharmaceutical Sciences 2006" />
     <property name="journalTitle" value="Journal of Pharmaceutical Sciences" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="00223549" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

    <property name="Bioelectromagnetics2006">
     <property name="title" value="Bioelectromagnetics 2006" />
     <property name="journalTitle" value="" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="01978462" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

    <property name="JournalofOrthopaedicResearch2006">
     <property name="title" value="Journal of Orthopaedic Research 2006" />
     <property name="journalTitle" value="Journal of Orthopaedic Research" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="07360266" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

    <property name="MassSpectrometryReviews2006">
     <property name="title" value="Mass Spectrometry Reviews 2006" />
     <property name="journalTitle" value="Mass Spectrometry Reviews" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="02777037" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

    <property name="Glia2006">
     <property name="title" value="Glia 2006" />
     <property name="journalTitle" value="Glia" />
     <property name="plugin" value="org.lockss.plugin.wiley.WileySourcePlugin" />
     <property name="param.1">
      <property name="key" value="base_url" />
      <property name="value" value="http://www2.lockss.org:8001/" />
     </property>
     <property name="param.2">
      <property name="key" value="year" />
      <property name="value" value="2006" />
     </property>
     <property name="param.3">
      <property name="key" value="journal_id" />
      <property name="value" value="08941491" />
     </property>
     <property name="attributes.publisher" value="Wiley" />
    </property>

  </property>
</lockss-config>
