<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)+>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="American Society for Pharmacology and Experimental Therapeutics">
   <property name="name" value="All American Society for Pharmacology and Experimental Therapeutics Titles" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='American Society for Pharmacology and Experimental Therapeutics']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="DrugMetabolismandDisposition1">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 1" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="1" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition2">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 2" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="2" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition3">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 3" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="3" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition4">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 4" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="4" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition5">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 5" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="5" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition6">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 6" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="6" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition7">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 7" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="7" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition8">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 8" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="8" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition9">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 9" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="9" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition10">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 10" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="10" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition11">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 11" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="11" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition12">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 12" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="12" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition13">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 13" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="13" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition14">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 14" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="14" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition15">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 15" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="15" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition16">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 16" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="16" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition17">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 17" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="17" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition18">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 18" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="18" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition19">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 19" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="19" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition20">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 20" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="20" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition21">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 21" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="21" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition22">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 22" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="22" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition23">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 23" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="23" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition24">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 24" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="24" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition25">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 25" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="25" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition26">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 26" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="26" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition27">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 27" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="27" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition28">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 28" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="28" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition29">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 29" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="29" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition30">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 30" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="30" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition31">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 31" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="31" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition32">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 32" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWirePressH20Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="32" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition33">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 33" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="33" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition34">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 34" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="volume_name" />
    <property name="value" value="34" />
   </property>
  </property>

  <property name="DrugMetabolismandDisposition35">
   <property name="attributes.publisher" value="American Society for Pharmacology and Experimental Therapeutics" />
   <property name="journalTitle" value="Drug Metabolism and Disposition" />
   <property name="issn" value="0090-9556" />
   <property name="eissn" value="1521-009X" />
   <property name="title" value="Drug Metabolism and Disposition Volume 35" />
   <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dmd.aspetjournals.org/" />
   </property>
   <property name="param.2">