<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
  <!ELEMENT lockss-config (if|property)+>
  <!ELEMENT property (property|list|value|if)*>
  <!ELEMENT list (value)+>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT test EMPTY>
  <!ELEMENT and (and|or|not|test)*>
  <!ELEMENT or (and|or|not|test)*>
  <!ELEMENT not (and|or|not|test)*>
  <!ELEMENT if (and|or|not|then|else|property)*>
  <!ELEMENT then (property)*>
  <!ELEMENT else (property)*>
  <!ATTLIST property name CDATA #REQUIRED>
  <!ATTLIST property value CDATA #IMPLIED>
  <!ATTLIST test hostname CDATA #IMPLIED>
  <!ATTLIST test group CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST test daemonVersion CDATA #IMPLIED>
  <!ATTLIST test platformVersionMin CDATA #IMPLIED>
  <!ATTLIST test platformVersionMax CDATA #IMPLIED>
  <!ATTLIST test platformVersion CDATA #IMPLIED>
  <!ATTLIST if hostname CDATA #IMPLIED>
  <!ATTLIST if group CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST if daemonVersion CDATA #IMPLIED>
  <!ATTLIST if platformVersionMin CDATA #IMPLIED>
  <!ATTLIST if platformVersionMax CDATA #IMPLIED>
  <!ATTLIST if platformVersion CDATA #IMPLIED>
]>

<lockss-config>
  <property name="org.lockss.title">

      <property name="BePresshttp//wwwbepresscom/asjcl2"> 
        <property name="title" value="http://www.bepress.com/asjcl Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/asjcl" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Asian Journal of Comparative Law" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/bejeap7"> 
        <property name="title" value="http://www.bepress.com/bejeap Volume 7" />
        <property name="journalTitle" value="http://www.bepress.com/bejeap" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="7" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The B.E. Journal of Economic Analysis &amp; Policy" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/bejm7"> 
        <property name="title" value="http://www.bepress.com/bejm Volume 7" />
        <property name="journalTitle" value="http://www.bepress.com/bejm" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="7" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The B.E. Journal of Macroeconomics" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/bejte7"> 
        <property name="title" value="http://www.bepress.com/bejte Volume 7" />
        <property name="journalTitle" value="http://www.bepress.com/bejte" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="7" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The B.E. Journal of Theoretical Economics" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/bis2"> 
        <property name="title" value="http://www.bepress.com/bis Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/bis" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Basic Income Studies" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/cas2"> 
        <property name="title" value="http://www.bepress.com/cas Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/cas" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Capitalism and Society" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/cppm2"> 
        <property name="title" value="http://www.bepress.com/cppm Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/cppm" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Chemical Product and Process Modeling" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ev4"> 
        <property name="title" value="http://www.bepress.com/ev Volume 4" />
        <property name="journalTitle" value="http://www.bepress.com/ev" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="4" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The Economists&apos; Voice" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/forum5"> 
        <property name="title" value="http://www.bepress.com/forum Volume 5" />
        <property name="journalTitle" value="http://www.bepress.com/forum" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="5" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The Forum" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/fhep10"> 
        <property name="title" value="http://www.bepress.com/fhep Volume 10" />
        <property name="journalTitle" value="http://www.bepress.com/fhep" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="10" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Forum for Health Economics &amp; Policy" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/gej7"> 
        <property name="title" value="http://www.bepress.com/gej Volume 7" />
        <property name="journalTitle" value="http://www.bepress.com/gej" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="7" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Global Economy Journal" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/gj7"> 
        <property name="title" value="http://www.bepress.com/gj Volume 7" />
        <property name="journalTitle" value="http://www.bepress.com/gj" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="7" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Global Jurist" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ice5"> 
        <property name="title" value="http://www.bepress.com/ice Volume 5" />
        <property name="journalTitle" value="http://www.bepress.com/ice" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="5" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="International Commentary on Evidence" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ijb3"> 
        <property name="title" value="http://www.bepress.com/ijb Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/ijb" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="3" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="The International Journal of Biostatistics" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ijcre5"> 
        <property name="title" value="http://www.bepress.com/ijcre Volume 5" />
        <property name="journalTitle" value="http://www.bepress.com/ijcre" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="5" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="International Journal of Chemical Reactor Engineering" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ijeeps8"> 
        <property name="title" value="http://www.bepress.com/ijeeps Volume 8" />
        <property name="journalTitle" value="http://www.bepress.com/ijeeps" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="8" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="International Journal of Emerging Electric Power Systems" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ijfe3"> 
        <property name="title" value="http://www.bepress.com/ijfe Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/ijfe" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="3" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="International Journal of Food Engineering" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/ijnes4"> 
        <property name="title" value="http://www.bepress.com/ijnes Volume 4" />
        <property name="journalTitle" value="http://www.bepress.com/ijnes" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="4" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="International Journal of Nursing Education Scholarship" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jafio5"> 
        <property name="title" value="http://www.bepress.com/jafio Volume 5" />
        <property name="journalTitle" value="http://www.bepress.com/jafio" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="5" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Agricultural &amp; Food Industrial Organization" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jbvela2"> 
        <property name="title" value="http://www.bepress.com/jbvela Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/jbvela" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Business Valuation and Economic Loss Analysis" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jcim4"> 
        <property name="title" value="http://www.bepress.com/jcim Volume 4" />
        <property name="journalTitle" value="http://www.bepress.com/jcim" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="4" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Complementary and Integrative Medicine" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jhsem4"> 
        <property name="title" value="http://www.bepress.com/jhsem Volume 4" />
        <property name="journalTitle" value="http://www.bepress.com/jhsem" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="4" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Homeland Security and Emergency Management" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jirspa2"> 
        <property name="title" value="http://www.bepress.com/jirspa Volume 2" />
        <property name="journalTitle" value="http://www.bepress.com/jirspa" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Imagery Research in Sport and Physical Activity" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jioe1"> 
        <property name="title" value="http://www.bepress.com/jioe Volume 1" />
        <property name="journalTitle" value="http://www.bepress.com/jioe" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Industrial Organization Education" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//servicesbepresscom/jpd1"> 
        <property name="title" value="http://services.bepress.com/jpd Volume 1" />
        <property name="journalTitle" value="http://services.bepress.com/jpd" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Public Deliberation" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jqas3"> 
        <property name="title" value="http://www.bepress.com/jqas Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/jqas" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="3" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Quantitative Analysis in Sports" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/jtl1"> 
        <property name="title" value="http://www.bepress.com/jtl Volume 1" />
        <property name="journalTitle" value="http://www.bepress.com/jtl" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Journal of Tort Law" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/mwjhr3"> 
        <property name="title" value="http://www.bepress.com/mwjhr Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/mwjhr" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="3" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Muslim World Journal of Human Rights" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/peps12"> 
        <property name="title" value="http://www.bepress.com/peps Volume 12" />
        <property name="journalTitle" value="http://www.bepress.com/peps" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="12" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Peace Economics, Peace Science and Public Policy" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/rle3"> 
        <property name="title" value="http://www.bepress.com/rle Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/rle" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="3" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Review of Law &amp; Economics" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/romsjournal5"> 
        <property name="title" value="http://www.bepress.com/romsjournal Volume 5" />
        <property name="journalTitle" value="http://www.bepress.com/romsjournal" />
        <property name="plugin" value="org.lockss.plugin.bepress.BePressPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://www.bepress.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="5" />
        </property>
        <property name="param.3">
          <property name="key" value="journal_abbr" />
          <property name="value" value="Review of Marketing Science" />
        </property>
        <property name="attributes.publisher" value="Berkeley Electronic Press" />
      </property>

       <property name="BePresshttp//wwwbepresscom/rmeef3"> 
        <property name="title" value="http://www.bepress.com/rmeef Volume 3" />
        <property name="journalTitle" value="http://www.bepress.com/rmeef" />