<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)+>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Big Bridge">
   <property name="name" value="All Big Bridge Titles" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='Big Bridge']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="BigBridge1">
   <property name="attributes.publisher" value="Big Bridge" />
   <property name="journalTitle" value="Big Bridge" />
   <property name="title" value="Big Bridge Volume 1" />
   <property name="plugin" value="edu.wisc.library.plugin.BigBridgeVol1Plugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.bigbridge.org/" />
   </property>
  </property>

  <property name="BigBridge2">
   <property name="attributes.publisher" value="Big Bridge" />
   <property name="journalTitle" value="Big Bridge" />
   <property name="title" value="Big Bridge Volume 2" />
   <property name="plugin" value="edu.wisc.library.plugin.BigBridgePlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.bigbridge.org/" />
   </property>
   <property name="param.2">
    <property name="key" value="num_issue_range" />
    <property name="value" value="5-8" />
   </property>
   <property name="param.3">
    <property name="key" value="volume" />
    <property name="value" value="2" />
   </property>
  </property>

 </property>

</lockss-config>
