<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)+>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Chemistry Central">
   <property name="name" value="All Chemistry Central Titles" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='Chemistry Central']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="ChemistryCentralJournal1">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Chemistry Central Journal" />
   <property name="title" value="Chemistry Central Journal Volume 1" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.journal.chemistrycentral.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1752-153X" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="1" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="ChemistryCentralJournal2">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Chemistry Central Journal" />
   <property name="title" value="Chemistry Central Journal Volume 2" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.journal.chemistrycentral.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1752-153X" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="2" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="ChemistryCentralJournal3">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Chemistry Central Journal" />
   <property name="title" value="Chemistry Central Journal Volume 3" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.journal.chemistrycentral.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1752-153X" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="3" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="ChemistryCentralJournal4">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Chemistry Central Journal" />
   <property name="title" value="Chemistry Central Journal Volume 4" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.journal.chemistrycentral.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1752-153X" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="4" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="JournalofCheminformatics1">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Journal of Cheminformatics" />
   <property name="title" value="Journal of Cheminformatics Volume 1" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.jcheminf.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1758-2946" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="1" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="JournalofCheminformatics2">
   <property name="attributes.publisher" value="Chemistry Central" />
   <property name="journalTitle" value="Journal of Cheminformatics" />
   <property name="title" value="Journal of Cheminformatics Volume 2" />
   <property name="plugin" value="org.lockss.plugin.bmc.BioMedCentralPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.jcheminf.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_issn" />
    <property name="value" value="1758-2946" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="2" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

 </property>

</lockss-config>
