<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)+>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Drogo Research">
   <property name="name" value="All Drogo Research Titles" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='Drogo Research']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="InternationalJournalofPsychiatricNursingResearch">
   <property name="attributes.publisher" value="Drogo Research" />
   <property name="journalTitle" value="International Journal of Psychiatric Nursing Research" />
   <property name="title" value="International Journal of Psychiatric Nursing Research" />
   <property name="plugin" value="uk.org.lockss.plugin.drogoresearch.DrogoResearchPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.drogoresearch.com/" />
   </property>
   <property name="param.99">
    <property name="key" value="pub_down" />
    <property name="value" value="true" />
   </property>
   <property name="attributes.rights" value="openaccess" />
  </property>

 </property>

</lockss-config>
