<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
  <!ELEMENT lockss-config (if|property)+>
  <!ELEMENT property (property|list|value|if)*>
  <!ELEMENT list (value)+>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT test EMPTY>
  <!ELEMENT and (and|or|not|test)*>
  <!ELEMENT or (and|or|not|test)*>
  <!ELEMENT not (and|or|not|test)*>
  <!ELEMENT if (and|or|not|then|else|property)*>
  <!ELEMENT then (property)*>
  <!ELEMENT else (property)*>
  <!ATTLIST property name CDATA #REQUIRED>
  <!ATTLIST property value CDATA #IMPLIED>
  <!ATTLIST test hostname CDATA #IMPLIED>
  <!ATTLIST test group CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST test daemonVersion CDATA #IMPLIED>
  <!ATTLIST test platformVersionMin CDATA #IMPLIED>
  <!ATTLIST test platformVersionMax CDATA #IMPLIED>
  <!ATTLIST test platformVersion CDATA #IMPLIED>
  <!ATTLIST if hostname CDATA #IMPLIED>
  <!ATTLIST if group CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST if daemonVersion CDATA #IMPLIED>
  <!ATTLIST if platformVersionMin CDATA #IMPLIED>
  <!ATTLIST if platformVersionMax CDATA #IMPLIED>
  <!ATTLIST if platformVersion CDATA #IMPLIED>
]>

<lockss-config>
  <property name="org.lockss.title">

      <property name="HighwireAmericanJournalofHospiceandPalliativeMedicine22"> 
        <property name="title" value="American Journal of Hospice and Palliative Medicine Volume 22" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajh.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="22" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofHospiceandPalliativeMedicine23"> 
        <property name="title" value="American Journal of Hospice and Palliative Medicine Volume 23" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajh.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="23" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofHospiceandPalliativeMedicine24"> 
        <property name="title" value="American Journal of Hospice and Palliative Medicine Volume 24" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajh.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="24" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofLifestyleMedicine1"> 
        <property name="title" value="American Journal of Lifestyle Medicine Volume 1" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajl.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofMedicalQuality20"> 
        <property name="title" value="American Journal of Medical Quality Volume 20" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajm.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="20" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofMedicalQuality21"> 
        <property name="title" value="American Journal of Medical Quality Volume 21" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajm.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="21" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofMedicalQuality22"> 
        <property name="title" value="American Journal of Medical Quality Volume 22" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajm.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="22" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanJournalofMen'sHealth1"> 
        <property name="title" value="American Journal of Men's Health Volume 1" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://jmh.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanJournalofSportsMedicine33"> 
        <property name="title" value="The American Journal of Sports Medicine Volume 33" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajs.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="33" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanJournalofSportsMedicine34"> 
        <property name="title" value="The American Journal of Sports Medicine Volume 34" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajs.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="34" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanJournalofSportsMedicine35"> 
        <property name="title" value="The American Journal of Sports Medicine Volume 35" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajs.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="35" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanJournalofSportsMedicine36"> 
        <property name="title" value="The American Journal of Sports Medicine Volume 36" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ajs.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="36" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanPoliticsResearch35"> 
        <property name="title" value="American Politics Research Volume 35" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://apr.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="35" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanPoliticsResearch36"> 
        <property name="title" value="American Politics Research Volume 36" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://apr.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="36" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAmericanPoliticsResearch37"> 
        <property name="title" value="American Politics Research Volume 37" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://apr.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="37" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanReviewofPublicAdministration35"> 
        <property name="title" value="The American Review of Public Administration Volume 35" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://arp.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="35" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanReviewofPublicAdministration36"> 
        <property name="title" value="The American Review of Public Administration Volume 36" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://arp.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="36" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheAmericanReviewofPublicAdministration37"> 
        <property name="title" value="The American Review of Public Administration Volume 37" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://arp.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="37" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAngiology56"> 
        <property name="title" value="Angiology Volume 56" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ang.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="56" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAngiology57"> 
        <property name="title" value="Angiology Volume 57" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ang.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="57" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAngiology58"> 
        <property name="title" value="Angiology Volume 58" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ang.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="58" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAnimation1"> 
        <property name="title" value="Animation Volume 1" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://anm.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="1" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireAnimation2"> 
        <property name="title" value="Animation Volume 2" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWireStrVolPlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://anm.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="2" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience598"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 598" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="598" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience599"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 599" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="599" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience600"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 600" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="600" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience601"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 601" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="601" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience602"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 602" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="602" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience603"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 603" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="603" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience604"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 604" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="604" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience605"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 605" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="605" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience606"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 606" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="606" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience607"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 607" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="607" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience608"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 608" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="608" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience609"> 
        <property name="title" value="The ANNALS of the American Academy of Political and Social Science Volume 609" />
        <property name="plugin" value="org.lockss.plugin.highwire.HighWirePlugin" />
        <property name="param.1">
          <property name="key" value="base_url" />
          <property name="value" value="http://ann.sagepub.com/" />
        </property>
        <property name="param.2">
          <property name="key" value="volume" />
          <property name="value" value="609" />
        </property>
        <property name="attributes.publisher" value="sage" />
        <property name="attributes.hint_application/pdf_filter_factory"   value="org.lockss.plugin.highwire.SagePublicationsPdfTransform$Simplified" />
      </property>

       <property name="HighwireTheANNALSoftheAmericanAcademyofPoliticalandSocialScience610"> 